version: "3.9"

services:
  app:
    image: mcr.microsoft.com/devcontainers/java:17
    container_name: finance-core-app
    volumes:
      - ..:/workspace:cached
    working_dir: /workspace
    command: sleep infinity
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: finance-core-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: finance
      POSTGRES_USER: finance_user
      POSTGRES_PASSWORD: finance_pass
    ports:
      - "5432:5432"
